[build-system]
requires = ["meson", "meson-python", "pybind11"]
build-backend = "mesonpy"

[project]
name = "FlexSIPP"
version = "1.0.0"
dependencies = [
    "numpy>=2.4.2",
    "matplotlib>=3.10.8",
    "sortedcontainers>=2.4.0",
    "tqdm>=4.67.3",
    "python-rapidjson>=1.23"
]
readme = "README.md"
authors = [
    {name = "Eric Kemmeren"},
    {name = "Issa Hanou"}
]
description = "Implementation of Flexibile Any-Start-Time Safe Interval Path Planning"

[project.urls]
Repository = "https://github.com/EricKemmeren/FlexSIPP"
